apiVersion: v2
name: artemis-edge-acm-demo
description: AMQ Broker edge federation on RHACM-managed SNO clusters
type: application
version: 0.3.0
appVersion: "7.14.1"
keywords:
  - amq
  - artemis
  - edge
  - rhacm
  - federation
  - gitops
maintainers:
  - name: Tosin Akinosho
