apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: openshift-gitops
spec:
  description: Global Hub push of regional hub config
  sourceRepos:
    - https://github.com/tosin2013/artemis-edge-acm-demo.git
  destinations:
    - namespace: "*"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
