apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - applicationsets/appproject-platform.yaml
  - applicationsets/hubs.yaml
  - platform/placements/all-hubs.yaml
  - platform/placements/binding-managed-hubs.yaml
  - platform/policies/openshift-gitops-operator.yaml
