apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-enable-uwm
  namespace: open-cluster-management
spec:
  disabled: false
  remediationAction: enforce
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: enable-user-workload-monitoring
        spec:
          remediationAction: enforce
          severity: medium
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: ConfigMap
                metadata:
                  name: cluster-monitoring-config
                  namespace: openshift-monitoring
                data:
                  config.yaml: |
                    enableUserWorkload: true
