apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: artemis-edge-workloads
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: edge-sno-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: "artemis-edge-{{name}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/tosin2013/artemis-edge-acm-demo.git
        targetRevision: main
        path: "."
        helm:
          valueFiles:
            - values.yaml
          parameters:
            - name: global.clusterDomain
              value: "{{metadata.labels.clusterDomain}}"
      destination:
        server: "{{server}}"
        namespace: artemis
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
