apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: edge-sno-policies
policyDefaults:
  namespace: ztp-policies
  placement:
    labelSelector:
      sites: "edge-sno"
  remediationAction: enforce
  severity: high
policies:
  - name: edge-common-config
    manifests:
      - path: common/
  - name: edge-amq-broker
    manifests:
      - path: edge-broker/
