{{- if .Values.amqBrokerOperator.enabled }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq-broker-rhel8
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "artemis-edge.labels" . | nindent 4 }}
spec:
  channel: {{ .Values.amqBrokerOperator.channel | quote }}
  installPlanApproval: Automatic
  name: amq-broker-rhel8
  source: {{ .Values.amqBrokerOperator.source }}
  sourceNamespace: openshift-marketplace
{{- end }}
