{{- if and .Values.tls.enabled .Values.tls.certManager.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: artemis-selfsigned-issuer
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    {{- include "artemis-edge.labels" . | nindent 4 }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: artemis-ca
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    {{- include "artemis-edge.labels" . | nindent 4 }}
spec:
  isCA: true
  commonName: artemis-edge-ca
  secretName: artemis-ca-secret
  duration: 8760h
  renewBefore: 720h
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: artemis-selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: artemis-ca-issuer
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    {{- include "artemis-edge.labels" . | nindent 4 }}
spec:
  ca:
    secretName: artemis-ca-secret
{{- if .Values.keycloak.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: artemis-selfsigned-issuer
  namespace: {{ .Values.keycloak.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    {{- include "artemis-edge.labels" . | nindent 4 }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: artemis-ca
  namespace: {{ .Values.keycloak.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    {{- include "artemis-edge.labels" . | nindent 4 }}
spec:
  isCA: true
  commonName: artemis-edge-ca
  secretName: artemis-ca-secret
  duration: 8760h
  renewBefore: 720h
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: artemis-selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: artemis-ca-issuer
  namespace: {{ .Values.keycloak.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    {{- include "artemis-edge.labels" . | nindent 4 }}
spec:
  ca:
    secretName: artemis-ca-secret
{{- end }}
{{- end }}
