{{- if .Values.externalSecrets.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    {{- include "artemis-edge.labels" . | nindent 4 }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.externalSecrets.gcpProjectID }}
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: {{ .Values.externalSecrets.gcpSASecretName }}
            namespace: {{ .Values.externalSecrets.gcpSASecretNamespace }}
            key: service-account-key
{{- end }}
