{{- if and .Values.tls.enabled (not .Values.tls.certManager.enabled) }}
{{- range .Values.hubBrokers }}
---
apiVersion: v1
kind: Secret
metadata:
  name: broker-tls-secret
  namespace: {{ $.Values.global.namespace }}
  labels:
    {{- include "artemis-edge.labels" $ | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    argocd.argoproj.io/sync-options: Replace=true
type: Opaque
data:
  {{- if $.Values.tls.hubKeystoreBase64 }}
  broker.ks: {{ $.Values.tls.hubKeystoreBase64 }}
  {{- else }}
  broker.ks: ""
  {{- end }}
  {{- if $.Values.tls.hubTruststoreBase64 }}
  client.ts: {{ $.Values.tls.hubTruststoreBase64 }}
  {{- else }}
  client.ts: ""
  {{- end }}
stringData:
  keyStorePassword: {{ $.Values.tls.keystorePassword | quote }}
  trustStorePassword: {{ $.Values.tls.truststorePassword | quote }}
{{- end }}
{{- end }}
