{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: {{ .Values.keycloak.namespace }}
  labels:
    {{- include "artemis-edge.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.keycloak.db.username | quote }}
  password: {{ .Values.keycloak.db.password | quote }}
{{- end }}
