apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    {{- include "artemis-edge.labels" . | nindent 4 }}
---
{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.keycloak.namespace }}
  labels:
    {{- include "artemis-edge.labels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.monitoring.namespace }}
  labels:
    {{- include "artemis-edge.labels" . | nindent 4 }}
{{- end }}
