apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-operators
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    {{- include "artemis-edge.labels" . | nindent 4 }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.gitops.repoURL }}
    targetRevision: {{ .Values.gitops.revision }}
    path: charts/operators
    helm:
      values: |
        global:
          namespace: {{ .Values.global.namespace | quote }}
        amqBrokerOperator:
          enabled: {{ .Values.amqBrokerOperator.enabled }}
          channel: {{ .Values.amqBrokerOperator.channel | quote }}
          source: {{ .Values.amqBrokerOperator.source | quote }}
        keycloak:
          enabled: {{ .Values.keycloak.enabled }}
          namespace: {{ .Values.keycloak.namespace | quote }}
        monitoring:
          enabled: {{ .Values.monitoring.enabled }}
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 10
      backoff:
        duration: 5s
        maxDuration: 3m
        factor: 2
