{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    {{- include "artemis-edge.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-artemis
  labels:
    {{- include "artemis-edge.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
      - nodes/metrics
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - configmaps
    verbs: ["get"]
  - apiGroups:
      - networking.k8s.io
      - extensions
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-artemis
  labels:
    {{- include "artemis-edge.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-artemis
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: {{ .Values.monitoring.namespace }}
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    {{- include "artemis-edge.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.monitoring.prometheus.replicas }}
  serviceAccountName: prometheus
  podMonitorSelector: {}
  serviceMonitorSelector:
    matchLabels:
      application-type: artemis
  resources:
    requests:
      memory: {{ .Values.monitoring.prometheus.memoryRequest | quote }}
  enableAdminAPI: false
{{- end }}
