apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-workloads
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    {{- include "artemis-edge.labels" . | nindent 4 }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.gitops.repoURL }}
    targetRevision: {{ .Values.gitops.revision }}
    path: charts/workloads
    helm:
      values: |
        {{- .Values | toYaml | nindent 8 }}
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 20
      backoff:
        duration: 10s
        maxDuration: 5m
        factor: 2
