#!/usr/bin/env bash
set -euo pipefail
#
# scripts/generate-secrets.sh — Generate agnosticd-v2-secrets from a GCP key + GUID
#
# Called by bootstrap.sh via the "Generate secrets from GCP key" setup step.
# Reads the service account JSON to extract project_id and client_email,
# then writes a populated secrets file. Preserves ocp4_pull_secret from
# any existing secrets file.
#
# Usage:
#   ./scripts/generate-secrets.sh <gcp-key-path> <guid> <account> <agnosticd-root>
#
# Example:
#   ./scripts/generate-secrets.sh ~/gcp-service-account.json bvzkf openenv-gcp ~/Development/agnosticd-v2

GCP_KEY_PATH="${1:?Usage: generate-secrets.sh <gcp-key-path> <guid> <account> <agnosticd-root>}"
GUID="${2:?Missing GUID}"
ACCOUNT="${3:?Missing account name}"
AGD_ROOT="${4:?Missing agnosticd-v2 root path}"

SECRETS_DIR="${AGD_ROOT}/../agnosticd-v2-secrets"
SECRETS_FILE="${SECRETS_DIR}/secrets-${ACCOUNT}.yml"

# Expand ~ in paths
GCP_KEY_PATH="${GCP_KEY_PATH/#\~/$HOME}"
SECRETS_DIR="${SECRETS_DIR/#\~/$HOME}"
SECRETS_FILE="${SECRETS_FILE/#\~/$HOME}"
AGD_ROOT="${AGD_ROOT/#\~/$HOME}"

# Validate key file
if [[ ! -f "$GCP_KEY_PATH" ]]; then
    echo "ERROR: GCP key file not found: $GCP_KEY_PATH" >&2
    exit 1
fi

# Extract fields from the service account JSON
read -r KEY_PROJECT_ID CLIENT_EMAIL < <(python3 -c "
import json, sys
with open(sys.argv[1]) as f:
    key = json.load(f)
print(key['project_id'], key['client_email'])
" "$GCP_KEY_PATH")

# For RHDP Open Environments, the sandbox project is openenv-<GUID>,
# not the parent project from the service account key.
PROJECT_ID="openenv-${GUID}"

echo "  Generating secrets for GUID=${GUID}, project=${PROJECT_ID}"
echo "  Service account: ${CLIENT_EMAIL} (key project: ${KEY_PROJECT_ID})"

# Derive sandbox values
BASE_DOMAIN="${GUID}.gcp.redhatworkshops.io"
GCP_CREDS_FILE="/secrets/gcp-key-${GUID}.json"

# Preserve pull secret from existing file if present
PULL_SECRET=""
if [[ -f "$SECRETS_FILE" ]]; then
    PULL_SECRET=$(python3 -c "
import yaml, sys
try:
    with open(sys.argv[1]) as f:
        data = yaml.safe_load(f)
    ps = data.get('ocp4_pull_secret', '')
    if ps and ps != '{\"auths\":{\"cloud.openshift.com\":{\"auth\":\"...\"}}}':
        print(ps.strip())
except Exception:
    pass
" "$SECRETS_FILE" 2>/dev/null || true)
    if [[ -n "$PULL_SECRET" ]]; then
        echo "  Preserved existing ocp4_pull_secret from ${SECRETS_FILE}"
    fi
fi

# Preserve org/billing settings from existing file if present
read -r FOLDER_ID COST_CENTER BILLING_ACCOUNT ORG_ID REQUESTER_EMAIL < <(python3 -c "
import yaml, sys
try:
    with open(sys.argv[1]) as f:
        data = yaml.safe_load(f)
    print(
        data.get('gcp_open_env_folder_id', ''),
        data.get('gcp_cost_center', ''),
        data.get('gcp_billing_account_id', ''),
        data.get('gcp_organization', ''),
        data.get('requester_email', '')
    )
except Exception:
    print('    ')
" "$SECRETS_FILE" 2>/dev/null || echo "    ")

# Defaults if not preserved
: "${FOLDER_ID:=178296823511}"
: "${COST_CENTER:=542}"
: "${BILLING_ACCOUNT:=018E14-C10C66-5F7BC2}"
: "${ORG_ID:=54643501348}"
: "${REQUESTER_EMAIL:=takinosh@redhat.com}"

mkdir -p "$SECRETS_DIR"

cat > "$SECRETS_FILE" <<SECRETS
---
# Generated by scripts/generate-secrets.sh for GUID ${GUID}
# DO NOT commit this file to Git.

base_domain: "${BASE_DOMAIN}"
gcp_project_id: "${PROJECT_ID}"
gcp_region: "us-east1"
gcp_service_account: "${CLIENT_EMAIL}"
gcp_credentials_file: "${GCP_CREDS_FILE}"

# RHDP Open Environment platform variables
agnosticd_open_environment: false
requester_email: "${REQUESTER_EMAIL}"
gcp_open_env_folder_id: "${FOLDER_ID}"
gcp_cost_center: "${COST_CENTER}"
gcp_billing_account_id: "${BILLING_ACCOUNT}"
gcp_admin_group: "group:rhdp-gcp-admins@redhat.com"
project_name: "${PROJECT_ID}"
gcp_organization: "${ORG_ID}"
gcp_root_dns_zone: "gcp.redhatworkshops.io"
service_account_email: "${CLIENT_EMAIL}"

# OpenShift pull secret
ocp4_pull_secret: >-
  ${PULL_SECRET:-\{"auths":\{"cloud.openshift.com":\{"auth":"..."\}\}\}}

# Note: GCP RHEL cloud images have repos pre-configured via RHUI.
# Satellite settings are not needed for GCP deployments.
SECRETS

echo "  Wrote ${SECRETS_FILE}"
