#!/usr/bin/env bash
set -euo pipefail
#
# Extract key deployment info from agnosticd-v2-output and write
# deployment-info.yml in the project root (git-ignored).
#
# Designed to be re-run after every cluster rebuild — always reads fresh
# data from provision-user-data.yaml and picks the newest kubeconfig.
#
# Usage:
#   ./scripts/save-deployment-info.sh [GUID]
#
# GUID is read from the first argument, AGD_GUID env var, or config.yml.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

if [[ -n "${1:-}" ]]; then
  GUID="$1"
elif [[ -n "${AGD_GUID:-}" ]]; then
  GUID="$AGD_GUID"
elif [[ -f "${PROJECT_ROOT}/config.yml" ]]; then
  GUID=$(python3 -c "import yaml; print(yaml.safe_load(open('${PROJECT_ROOT}/config.yml'))['agd_guid'])" 2>/dev/null) || true
fi
if [[ -z "${GUID:-}" ]]; then
  echo "ERROR: GUID required. Pass as argument, set AGD_GUID, or run bootstrap.sh first." >&2
  exit 1
fi
OUTPUT_DIR="${AGD_OUTPUT_DIR:-${HOME}/Development/agnosticd-v2-output/${GUID}}"
USER_DATA="${OUTPUT_DIR}/provision-user-data.yaml"
DEST="${PROJECT_ROOT}/deployment-info.yml"

if [[ ! -f "${USER_DATA}" ]]; then
  echo "ERROR: ${USER_DATA} not found." >&2
  echo "Run 'agd provision' first, or set AGD_OUTPUT_DIR." >&2
  exit 1
fi

if ! command -v python3 &>/dev/null; then
  echo "ERROR: python3 is required" >&2
  exit 1
fi

python3 - "${USER_DATA}" "${OUTPUT_DIR}" "${DEST}" <<'PYEOF'
import sys, yaml, os, glob

user_data_path = sys.argv[1]
output_dir     = sys.argv[2]
dest_path      = sys.argv[3]

with open(user_data_path) as f:
    data = yaml.safe_load(f)

guid = data.get("guid", "")

info = {
    "guid": guid,
    "cloud_provider": data.get("cloud_provider", ""),
    "openshift_api_url": data.get("openshift_api_url", ""),
    "openshift_console_url": data.get("openshift_console_url",
                             data.get("openshift_cluster_console_url", "")),
    "openshift_cluster_ingress_domain": data.get("openshift_cluster_ingress_domain", ""),
    "openshift_cluster_admin_username": data.get("openshift_cluster_admin_username", "kubeadmin"),
    "openshift_cluster_admin_password": data.get("openshift_cluster_admin_password",
                                       data.get("openshift_kubeadmin_password", "")),
    "bastion_public_hostname": data.get("bastion_public_hostname", ""),
    "bastion_ssh_user_name": data.get("bastion_ssh_user_name", ""),
    "bastion_ssh_password": data.get("bastion_ssh_password", ""),
    "openshift_gitops_server": data.get("openshift_gitops_server", ""),
}

# RHACM console URL — construct from ingress domain if not in user-data
rhacm_url = data.get("rhacm_console_url", "")
if not rhacm_url:
    domain = data.get("openshift_cluster_ingress_domain", "")
    if domain:
        rhacm_url = f"https://multicloud-console.apps.{domain.removeprefix('apps.')}"
info["rhacm_console_url"] = rhacm_url
info["rhacm_namespace"] = "open-cluster-management"

# Showroom URL — use first user's showroom URL if available
showroom_url = data.get("showroom_url", "")
users = data.get("users", {})
if not showroom_url and users:
    first_user = next(iter(users.values()), {})
    showroom_url = first_user.get("showroom_primary_view_url",
                   first_user.get("lab_ui_url", ""))
info["showroom_url"] = showroom_url

# GCP info
if data.get("gcp_project_id"):
    info["gcp_project_id"] = data["gcp_project_id"]
    info["gcp_region"] = data.get("gcp_region", "")
    info["gcp_console_url"] = data.get("gcp_console_url", "")

# Users section
if users:
    info["users"] = {}
    for name, u in users.items():
        user_info = {
            "password": u.get("password", ""),
            "login_command": u.get("login_command", ""),
        }
        if u.get("showroom_primary_view_url"):
            user_info["showroom_url"] = u["showroom_primary_view_url"]
        if u.get("lab_ui_url"):
            user_info["lab_ui_url"] = u["lab_ui_url"]
        info["users"][name] = user_info

# Kubeconfig — prefer the newest file matching *_GUID_kubeconfig
kubeconfig_matches = glob.glob(os.path.join(output_dir, f"*_{guid}_kubeconfig"))
if kubeconfig_matches:
    info["kubeconfig_path"] = max(kubeconfig_matches, key=os.path.getmtime)

with open(dest_path, "w") as f:
    f.write("# Generated by scripts/save-deployment-info.sh — DO NOT COMMIT\n")
    f.write("# Re-run the script to refresh after a new deployment\n")
    yaml.dump(info, f, default_flow_style=False, sort_keys=False)

print(f"Deployment info saved to: {dest_path}")
PYEOF
