#!/usr/bin/env bash
set -euo pipefail
#
# Extract key deployment info from agnosticd-v2-output and write
# deployment-info.yml in the project root (git-ignored).
#
# Usage:
#   ./scripts/save-deployment-info.sh [GUID]
#
# GUID defaults to the AGD_GUID environment variable or "artgcp".

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

GUID="${1:-${AGD_GUID:-artgcp}}"
OUTPUT_DIR="${AGD_OUTPUT_DIR:-${HOME}/Development/agnosticd-v2-output/${GUID}}"
USER_DATA="${OUTPUT_DIR}/provision-user-data.yaml"
DEST="${PROJECT_ROOT}/deployment-info.yml"

if [[ ! -f "${USER_DATA}" ]]; then
  echo "ERROR: ${USER_DATA} not found." >&2
  echo "Run 'agd provision' first, or set AGD_OUTPUT_DIR." >&2
  exit 1
fi

if ! command -v python3 &>/dev/null; then
  echo "ERROR: python3 is required" >&2
  exit 1
fi

python3 - "${USER_DATA}" "${OUTPUT_DIR}" "${DEST}" <<'PYEOF'
import sys, yaml, os

user_data_path = sys.argv[1]
output_dir     = sys.argv[2]
dest_path      = sys.argv[3]

with open(user_data_path) as f:
    data = yaml.safe_load(f)

info = {
    "guid": data.get("guid", ""),
    "cloud_provider": data.get("cloud_provider", ""),
    "openshift_api_url": data.get("openshift_api_url", ""),
    "openshift_console_url": data.get("openshift_console_url", ""),
    "openshift_cluster_ingress_domain": data.get("openshift_cluster_ingress_domain", ""),
    "openshift_cluster_admin_username": data.get("openshift_cluster_admin_username", ""),
    "openshift_cluster_admin_password": data.get("openshift_cluster_admin_password", ""),
    "bastion_public_hostname": data.get("bastion_public_hostname", ""),
    "bastion_ssh_user_name": data.get("bastion_ssh_user_name", ""),
    "bastion_ssh_password": data.get("bastion_ssh_password", ""),
    "openshift_gitops_server": data.get("openshift_gitops_server", ""),
    "rhacm_console_url": data.get("rhacm_console_url", ""),
    "rhacm_namespace": data.get("rhacm_namespace", ""),
    "showroom_url": data.get("showroom_url", ""),
}

if data.get("artemis_edge_namespace"):
    info["artemis_edge_namespace"] = data["artemis_edge_namespace"]
    info["artemis_edge_mode"] = data.get("artemis_edge_mode", "")
    info["artemis_edge_spoke_count"] = data.get("artemis_edge_spoke_count", "")
    info["artemis_edge_content_repo"] = data.get("artemis_edge_content_repo", "")

if data.get("gcp_project_id"):
    info["gcp_project_id"] = data["gcp_project_id"]
    info["gcp_region"] = data.get("gcp_region", "")
    info["gcp_console_url"] = data.get("gcp_console_url", "")

users = data.get("users", {})
if users:
    info["users"] = {}
    for name, u in users.items():
        user_info = {
            "password": u.get("password", ""),
            "login_command": u.get("login_command", ""),
        }
        if u.get("showroom_primary_view_url"):
            user_info["showroom_url"] = u["showroom_primary_view_url"]
        if u.get("lab_ui_url"):
            user_info["lab_ui_url"] = u["lab_ui_url"]
        info["users"][name] = user_info

kubeconfig = os.path.join(output_dir,
    f"openshift-cluster_{info['guid']}_kubeconfig")
if os.path.exists(kubeconfig):
    info["kubeconfig_path"] = kubeconfig

with open(dest_path, "w") as f:
    f.write("# Generated by scripts/save-deployment-info.sh — DO NOT COMMIT\n")
    f.write("# Re-run the script to refresh after a new deployment\n")
    yaml.dump(info, f, default_flow_style=False, sort_keys=False)

print(f"Deployment info saved to: {dest_path}")
PYEOF
