apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq-broker-rhel9
  namespace: artemis
spec:
  channel: "7.14.x"
  installPlanApproval: Automatic
  name: amq-broker-rhel9
  source: redhat-operators
  sourceNamespace: openshift-marketplace
