apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-openshift-gitops-operator
  namespace: open-cluster-management
spec:
  disabled: false
  remediationAction: enforce
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: openshift-gitops-operator
        spec:
          remediationAction: enforce
          severity: high
          complianceType: musthave
          upgradeApproval: Automatic
          subscription:
            channel: latest
            name: openshift-gitops-operator
            namespace: openshift-operators
            source: redhat-operators
            sourceNamespace: openshift-marketplace
